import { defineField, defineType } from "sanity";

export const siteSettingsType = defineType({
  name: "siteSettings",
  title: "Site Ayarları",
  type: "document",
  fields: [
    defineField({ name: "siteName", title: "Site Adı", type: "string", initialValue: "Tınaz Yapı", validation: (Rule) => Rule.required() }),
    defineField({ name: "siteTagline", title: "Slogan", type: "string", initialValue: "Adımızı kapıya yazıyoruz." }),
    defineField({
      name: "copyrightNotice",
      title: "Telif Metni",
      type: "string",
      description: "Footer'da yıl ve site adından sonra gösterilir.",
      initialValue: "Tüm hakları saklıdır.",
    }),
    defineField({
      name: "logo",
      title: "Logo",
      type: "image",
      options: { hotspot: true },
      description: "Önerilen: 400x120px (Yatay) veya 200x200px (Kare). Şeffaf PNG veya SVG tercih edilmelidir.",
      fields: [
        defineField({
          name: "alt",
          title: "Alternatif Metin",
          type: "string",
          description: "Görsel yüklenemediğinde görünecek olan yazı (Örn: Şirket Logo)",
        }),
      ],
    }),
    defineField({ name: "favicon", title: "Favicon", type: "image", description: "512x512px kare görsel önerilir." }),
    defineField({ name: "defaultOgImage", title: "Varsayılan OG Görseli", type: "image", description: "Sosyal medya paylaşımları için. 1200x630px." }),
    defineField({
      name: "defaultSeo",
      title: "Varsayılan SEO",
      type: "object",
      fields: [
        defineField({ name: "metaTitle", title: "Meta Başlık", type: "string", validation: (Rule) => Rule.max(60) }),
        defineField({ name: "metaDescription", title: "Meta Açıklama", type: "text", rows: 3, validation: (Rule) => Rule.max(160) }),
      ],
    }),
    defineField({
      name: "contactInfo",
      title: "İletişim Bilgileri",
      type: "object",
      fields: [
        defineField({ name: "phone", title: "Telefon", type: "string" }),
        defineField({ name: "email", title: "E-posta", type: "string" }),
        defineField({ name: "address", title: "Adres", type: "text", rows: 3 }),
        defineField({
          name: "whatsappNumber",
          title: "WhatsApp Numarası",
          type: "string",
          description: "Başında + ile ülke kodu dahil. Örn: +905001234567",
        }),
        defineField({
          name: "mapIframe",
          title: "Harita iFrame Kodu",
          type: "text",
          rows: 4,
          description: "Google Maps > Paylaş > Haritayı göm > HTML kodunu buraya yapıştır.",
        }),
      ],
    }),
    defineField({
      name: "salesOffice",
      title: "Satış Ofisi",
      type: "object",
      description: "Tüm projelerde görünen tek satış yetkilisi.",
      fields: [
        defineField({ name: "contactName", title: "Yetkili Adı", type: "string", initialValue: "Deniz Aksoy" }),
        defineField({ name: "contactRole", title: "Unvan", type: "string", initialValue: "Satış Ofisi" }),
        defineField({
          name: "photo",
          title: "Fotoğraf",
          type: "image",
          options: { hotspot: true },
          fields: [defineField({ name: "alt", title: "Alt Metni", type: "string" })],
        }),
        defineField({ name: "phone", title: "Telefon", type: "string", initialValue: "0212 000 00 00" }),
        defineField({
          name: "whatsappNumber",
          title: "WhatsApp",
          type: "string",
          description: "Başında + ile ülke kodu dahil. Örn: +905001234567",
          initialValue: "+905000000000",
        }),
        defineField({
          name: "workingHours",
          title: "Çalışma Saatleri",
          type: "string",
          initialValue: "Hafta içi 09:00–19:00, Cumartesi 10:00–17:00",
        }),
        defineField({
          name: "headline",
          title: "Bant Başlığı",
          type: "string",
          description: "Sayfa sonundaki satış ofisi bandının başlığı.",
          initialValue: "Bir daireyi yerinde görmek ister misiniz?",
        }),
        defineField({
          name: "bandImage",
          title: "Bant Görseli",
          type: "image",
          description: "Satış ofisi bandında başlığın yanında görünür. Akşam, ışığı yanan pencereler en iyi sonucu verir.",
          options: { hotspot: true },
          fields: [defineField({ name: "alt", title: "Alt Metni", type: "string" })],
        }),
        defineField({ name: "ctaLabel", title: "Buton Metni", type: "string", initialValue: "Satış ofisini arayın" }),
        defineField({ name: "whatsappLabel", title: "WhatsApp Buton Metni", type: "string", initialValue: "WhatsApp'tan yazın" }),
        defineField({
          name: "priceNote",
          title: "Fiyat Notu",
          type: "string",
          description: "Fiyat yerine gösterilen metin.",
          initialValue: "Fiyat bilgisi için satış ofisimizi arayın.",
        }),
      ],
    }),
    defineField({ name: "socialLinks", title: "Sosyal Medya Hesapları", type: "array", of: [{ type: "socialLink" }] }),
    defineField({ name: "gaId", title: "Google Analytics ID", type: "string", description: "Örn: G-XXXXXXXXXX" }),
    defineField({ name: "gtmId", title: "Google Tag Manager ID", type: "string", description: "Örn: GTM-XXXXXXX" }),
    defineField({
      name: "googleSearchConsoleId",
      title: "Google Search Console Doğrulama Kodu",
      type: "string",
      description: "Search Console meta etiketi içerisindeki 'content' değerini buraya girin. Örn: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    }),
  ],
  preview: { select: { title: "siteName" } },
});
